management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

### 注册当前服务到AdminUI-Server服务中
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080